# Generated by Django 6.0.6 on 2026-06-26 14:01

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NigeriaState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Nigerian State',
                'verbose_name_plural': 'Nigerian States',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NigeriaLGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('state_name', models.CharField(blank=True, max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lgas', to='npf_geo_incidents.nigeriastate')),
            ],
            options={
                'verbose_name': 'LGA',
                'verbose_name_plural': 'LGAs',
                'ordering': ['state_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Incident GPS coordinates (longitude, latitude)', srid=4326)),
                ('title', models.CharField(max_length=200)),
                ('incident_type', models.CharField(choices=[('theft', 'Theft / Robbery'), ('assault', 'Assault / Violence'), ('kidnapping', 'Kidnapping / Abduction'), ('terrorism', 'Terrorism / Insurgency'), ('fraud', 'Fraud / Cybercrime'), ('homicide', 'Homicide'), ('vandalism', 'Vandalism / Property Damage'), ('drug', 'Drug-Related'), ('sexual_offence', 'Sexual Offence'), ('traffic_offence', 'Traffic Offence'), ('other', 'Other')], default='other', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('reported_by', models.CharField(blank=True, help_text='Reporter name / badge number', max_length=150)),
                ('date_occurred', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('lga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='npf_geo_incidents.nigerialga')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='npf_geo_incidents.nigeriastate')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-date_reported'],
            },
        ),
    ]
