# Generated by Django 6.0.6 on 2026-06-26 14:34

import django.db.models.deletion
import npf_geo_incidents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npf_geo_incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='contact_details',
            field=npf_geo_incidents.models.EncryptedCharField(blank=True, help_text='Reporter phone / email', max_length=255),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=npf_geo_incidents.models.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='reported_by',
            field=npf_geo_incidents.models.EncryptedCharField(blank=True, help_text='Reporter name / badge number', max_length=255),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('national', 'National Officer'), ('state', 'State Officer'), ('lga', 'LGA Officer')], default='national', max_length=20)),
                ('assigned_lga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='npf_geo_incidents.nigerialga')),
                ('assigned_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='npf_geo_incidents.nigeriastate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
