# Generated by Django 6.0.6 on 2026-06-26 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npf_geo_incidents', '0002_incident_contact_details_alter_incident_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('face_embedding', models.TextField(blank=True, help_text='JSON array representing the facial feature vector')),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='suspects/faces/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lga_of_arrest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='npf_geo_incidents.nigerialga')),
                ('state_of_arrest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='npf_geo_incidents.nigeriastate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finger', models.CharField(choices=[('R_thumb', 'Right Thumb'), ('R_index', 'Right Index'), ('R_middle', 'Right Middle'), ('R_ring', 'Right Ring'), ('R_little', 'Right Little'), ('L_thumb', 'Left Thumb'), ('L_index', 'Left Index'), ('L_middle', 'Left Middle'), ('L_ring', 'Left Ring'), ('L_little', 'Left Little')], max_length=10)),
                ('minutiae_template', models.TextField(help_text='JSON representation of minutiae points')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='npf_geo_incidents.suspect')),
            ],
        ),
    ]
